// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.dow.domain;

import com.sut.dow.domain.Sell;

privileged aspect Sell_Roo_JavaBean {
    
    public String Sell.getName() {
        return this.name;
    }
    
    public void Sell.setName(String name) {
        this.name = name;
    }
    
}
